using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace 卓汇数据追溯系统
{
    public class HansData_U_Bracket
    {
        public bool HanDataUAResult = true;
        //public string location1_layer1_pulse_profile = "0";
        //public string location1_layer2_pulse_profile = "0";
        //public string location2_layer1_pulse_profile = "0";
        //public string location2_layer2_pulse_profile = "0";
        //public string location3_layer1_pulse_profile = "0";
        //public string location3_layer2_pulse_profile = "0";
        //public string location4_layer1_pulse_profile = "0";
        //public string location5_layer1_pulse_profile = "0";
        //public string location6_layer1_pulse_profile = "0";
        public string power_ll = "0";
        public string power_ul = "0";
        public string pattern_type = "0";
        public string spot_size = "0";
        public string hatch = "0";
        public string swing_amplitude = "0";
        public string swing_freq = "0";
        public string JudgeResult = "0";
        public string MeasureTime = "0";
        public string MachineSN = "0";
        public string PulseProfile_measure = "0";
        public string ActualPower = "0";
        public string Power_measure = "0";
        public string WaveForm_measure = "0";
        public string Frequency_measure = "0";
        public string LinearSpeed_measure = "0";
        public string QRelease_measure = "0";
        public string PulseEnergy_measure = "0";
        public string PeakPower_measure = "0";
        public string laser_sensor = "NA";
        public string pulse_profile = "0";
        public string location1_layer1_laser_power = "0";
        public string location1_layer1_frequency = "0";
        public string location1_layer1_waveform = "0";
        public string location1_layer1_pulse_energy = "0";
        public string location1_layer1_laser_speed = "0";
        public string location1_layer1_jump_speed = "0";
        public string location1_layer1_jump_delay = "0";
        public string location1_layer1_scanner_delay = "0";
        //public string location1_layer2_laser_power = "0";
        //public string location1_layer2_frequency = "0";
        //public string location1_layer2_waveform = "0";
        //public string location1_layer2_pulse_energy = "0";
        //public string location1_layer2_laser_speed = "0";
        //public string location1_layer2_jump_speed = "0";
        //public string location1_layer2_jump_delay = "0";
        //public string location1_layer2_scanner_delay = "0";

        public string location2_layer1_laser_power = "0";
        public string location2_layer1_frequency = "0";
        public string location2_layer1_waveform = "0";
        public string location2_layer1_pulse_energy = "0";
        public string location2_layer1_laser_speed = "0";
        public string location2_layer1_jump_speed = "0";
        public string location2_layer1_jump_delay = "0";
        public string location2_layer1_scanner_delay = "0";
        //public string location2_layer2_laser_power = "0";
        //public string location2_layer2_frequency = "0";
        //public string location2_layer2_waveform = "0";
        //public string location2_layer2_pulse_energy = "0";
        //public string location2_layer2_laser_speed = "0";
        //public string location2_layer2_jump_speed = "0";
        //public string location2_layer2_jump_delay = "0";
        //public string location2_layer2_scanner_delay = "0";

        public string location3_layer1_laser_power = "0";
        public string location3_layer1_frequency = "0";
        public string location3_layer1_waveform = "0";
        public string location3_layer1_pulse_energy = "0";
        public string location3_layer1_laser_speed = "0";
        public string location3_layer1_jump_speed = "0";
        public string location3_layer1_jump_delay = "0";
        public string location3_layer1_scanner_delay = "0";
        //public string location3_layer2_laser_power = "0";
        //public string location3_layer2_frequency = "0";
        //public string location3_layer2_waveform = "0";
        //public string location3_layer2_pulse_energy = "0";
        //public string location3_layer2_laser_speed = "0";
        //public string location3_layer2_jump_speed = "0";
        //public string location3_layer2_jump_delay = "0";
        //public string location3_layer2_scanner_delay = "0";

        public string location4_layer1_laser_power = "0";
        public string location4_layer1_frequency = "0";
        public string location4_layer1_waveform = "0";
        public string location4_layer1_pulse_energy = "0";
        public string location4_layer1_laser_speed = "0";
        public string location4_layer1_jump_speed = "0";
        public string location4_layer1_jump_delay = "0";
        public string location4_layer1_scanner_delay = "0";
        //public string location4_layer2_laser_power = "0";
        //public string location4_layer2_frequency = "0";
        //public string location4_layer2_waveform = "0";
        //public string location4_layer2_pulse_energy = "0";
        //public string location4_layer2_laser_speed = "0";
        //public string location4_layer2_jump_speed = "0";
        //public string location4_layer2_jump_delay = "0";
        //public string location4_layer2_scanner_delay = "0";

        //public string location5_layer1_laser_power = "0";
        //public string location5_layer1_frequency = "0";
        //public string location5_layer1_waveform = "0";
        //public string location5_layer1_pulse_energy = "0";
        //public string location5_layer1_laser_speed = "0";
        //public string location5_layer1_jump_speed = "0";
        //public string location5_layer1_jump_delay = "0";
        //public string location5_layer1_scanner_delay = "0";
        //public string location5_layer2_laser_power = "0";
        //public string location5_layer2_frequency = "0";
        //public string location5_layer2_waveform = "0";
        //public string location5_layer2_pulse_energy = "0";
        //public string location5_layer2_laser_speed = "0";
        //public string location5_layer2_jump_speed = "0";
        //public string location5_layer2_jump_delay = "0";
        //public string location5_layer2_scanner_delay = "0";

        //public string location6_layer1_laser_power = "0";
        //public string location6_layer1_frequency = "0";
        //public string location6_layer1_waveform = "0";
        //public string location6_layer1_pulse_energy = "0";
        //public string location6_layer1_laser_speed = "0";
        //public string location6_layer1_jump_speed = "0";
        //public string location6_layer1_jump_delay = "0";
        //public string location6_layer1_scanner_delay = "0";
        //public string location6_layer2_laser_power = "0";
        //public string location6_layer2_frequency = "0";
        //public string location6_layer2_waveform = "0";
        //public string location6_layer2_pulse_energy = "0";
        //public string location6_layer2_laser_speed = "0";
        //public string location6_layer2_jump_speed = "0";
        //public string location6_layer2_jump_delay = "0";
        //public string location6_layer2_scanner_delay = "0";
    }
}
